application: photo-glow
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /swan.jpg
  static_files: static/swan.jpg
  upload: static/swan.jpg
- url: /style.css
  static_files: static/style.css
  upload: static/style.css
